### ISSUE TITLE
Proper way to add a test_depend

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-joint-state-publisher#1]
The package has this in the `package.xml`:
```
<test_depend>rostest</test_depend>
```

I added `ros-melodic-rostest` in `ros_makedepends` in the PKGBUILD. Is this reasonable? Or does it need to be a depend as well?

**Comment by acxz** [comment]
hmmm, not sure. I have actually been leaving the test_depend packages out of the PKGBUILD all together. Maybe we can put them in `optdepends`?

**Comment by jwhendy** [comment]
I think these are required to run tests during building (I got a `cmake` error when trying to build), so I put it in `makedepends`. I think `optdepends` will only suggest installing after the build. My worry is if they are also needed by the package when running, which would mean we need them to be true `depends`. Not sure.

**Comment by acxz** [comment]
Okay then let's decide to but testdepends in the makedepends field. I'll go ahead and close this issue with that resolution.

**Comment by jwhendy** [comment]
Thanks @acxz . I was unsure above, but am not pretty confident in this approach, as ROS package.xml would specify them as true `<depends>` if they were needed post-build.
